<footer>
    <div>&copy; <?php echo date('Y'); ?> The Guitar Store</div>
    <div><!-- Date; dynamically generated by js --></div>
</footer>
<script src="/Assignment10/scripts/date.js"></script>
<script src="/Assignment10/scripts/customer_login.js"></script>